### ISSUE TITLE
'run FitNesse test' doesn't work

### ISSUE THREAD

**Issue by danielkroon** [chrisotto6/VSCodeFitNesse#109]
## 👣 Steps to reproduce
1. open a test in VS code.
2. right click in the test.
3. click 'Run FitNesse test'.
4. you receive an error that you should escape the & operator.
```
At line:1 char:201
+ ... age.Tagetik.TagetikPps.S0501PremiesClaimsKostenTest.wi?test^&format=t ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
```
5. escape the & operator.
6. press enter.
7. the test doesn't run but gives a list of commands I can use.

```
java -Xmx768m -jar D:\Users\1001949\Git\Tagetik\FitNesse\fitnesse-standalone.jar -p 8080 -d d:\Users\1001949\Git\Tagetik\FitNesse\ -c FrontPage.Tagetik.TagetikPps.S0501PremiesClaimsKostenTest.wi?test^("&")format=text
Usage: java -jar fitnesse.jar [-vpdrlfeoaicblh]
        -p <port number> {80}
        -d <working directory> {.}
        -r <page root directory> {FitNesseRoot}
        -l <log directory> {no logging}
        -f <config properties file> {plugins.properties}
        -e <days> {14} Number of days before page versions expire
        -o omit updates
        -a {user:pwd | user-file-name} enable authentication.
        -i Install only, then quit.
        -c <command> execute single command.
        -b <filename> redirect command output.
        -v {off} Verbose logging
        -lh {off} Only bind to loopback interface (localhost only access)
```
## 🔬 Expected behavior
I expect that the test start running in a new browser window.

## 🌳 Environment
 - OS: Windows10

**Comment by chrisotto6** [comment]
What version of Fitnesse jar are you using? Also please supply the `fitnesse` config from your settings the json file can be found here:

```Depending on your platform, the user settings file is located here:

Windows %APPDATA%\Code\User\settings.json```

**Comment by reators** [comment]
Hi Chris,

I observed the same error. I'm running the extension on Win10 with git-bash.
My settings are:

```
{
    ...
    "fitnesse.fitnesseJarLocation": "/c/Users/xcg4196/git/kf-infi-fitnesse/wiki/fitnesse-standalone.jar",
    "fitnesse.fitnessePort": "8090",
    "fitnesse.fitnesseRoot": "/c/Users/xcg4196/git/kf-infi-fitnesse/wiki/FitNesseRoot",
    "fitnesse.rootPath": "/c/Users/xcg4196/git/kf-infi-fitnesse/wiki/",
    ...
}
```
The command that is executed on right-click on a wiki file is
`java -Xmx768m -jar /c/Users/xcg4196/git/kf-infi-fitnesse/wiki/fitnesse-standalone.jar -p 8090 -d /c/User
s/xcg4196/git/kf-infi-fitnesse/wiki/ -r /c/Users/xcg4196/git/kf-infi-fitnesse/wiki/FitNesseRoot -d c:\Users\xcg4196\git\kf-infi-fitnesse\wiki\ -c ?test^&format=text`

I can see two additional problems which are not reported by the original poster:
* What is probably incorrect is the second appearance of option `-d` with a path that `fitnesse` probably doesn't understand
* The test in question isn't passed to the command line parameter `-c`

My versions:
* VS Code FitNesse extension:  `1.6.5`
* FitNesse: `20200205`

**Comment by chrisotto6** [comment]
@reators thanks for supplying the additional information, that should be helpful in fixing the issue. I admittedly have never used this with git-bash which may be cause for the two instances of '-d' one is the bash version the others is the windows syntax. I should be able to look into this over the weekend.

**Comment by reators** [comment]
Thanks, looking forward to this :)
