### ISSUE TITLE
DBFit '!' at start gets replaced

### ISSUE THREAD

**Issue by troyyer** [chrisotto6/VSCodeFitNesse#155]
## ✨ New feature description
When using the plugin in VS Code, if the Fitnesse test page is for a DBfit test, the ! for the connection and the query at the start of the line gets removed. The plugin should handle this

## ➕ Additional context
![dbfit content page](https://user-images.githubusercontent.com/28956675/86308368-5ce8df80-bc5c-11ea-9c54-dd88a7618175.gif)

## ➕ What benefit is there to be gained with this addition?
Writing and managing DBfit tests in VS code over writing them in the Fitnesse server editor

**Comment by chrisotto6** [comment]
@troyyer the vscode extension just does what FitNesse UI does up to a specific release. Does this work in the FitNesse UI?

**Comment by troyyer** [comment]
Hi @chrisotto6 , 
Thanks for getting back to me. Yes from the Fitnesse Wiki Editor I am able to create a test without the leading ! on the lines mentioned in my previous comment getting deleted on save in the Fitnesseeditor.
please see the below screengrab of the steps i did to create the test file in the editor
![Creating a dfFit test from the Fitnesse wiki editor](https://user-images.githubusercontent.com/28956675/86894197-17d61900-c146-11ea-8b07-7a35bcdb49b0.gif)
this is the screenshot when i click on Edit 
![image](https://user-images.githubusercontent.com/28956675/86894362-4eac2f00-c146-11ea-9a3b-5c65a26572e2.png)

As a work around, Is there a way to restrict the plugin to only perform the formatting when i ask it to (rather than on each save of the file)? I could then edit the file, press the key combination to format the file, then manually put back in the missing characters and then save it.

**Comment by chrisotto6** [comment]
You're only saving the test, what about when you format it. When I format your example in your first screenshot the leading `!` in `ConnectUsingFile` gets trimmed as well.

Before Format:
```wiki
!path lib/*.jar
!|dbfit.PostgresTest|
!|ConnectUsingFile|FitNesseRoot\Connection.bat|

|Query| select test from Test LIMIT 1|
|test|
|result|```

After Format:
```wiki
!path lib/*.jar
!|dbfit.PostgresTest                         |
|ConnectUsingFile|FitNesseRoot\Connection.bat|

|Query|select test from Test LIMIT 1|
|test                               |
|result                             |
```

I can look at making format on save configurable and make it enabled by default but I want to make sure that formatting in FitNesse and formatting in the extension are the same.

**Comment by troyyer** [comment]
Ah right. now I see  where I am going wrong. I did not have the right spacing in the file
if the file is written like this 
![image](https://user-images.githubusercontent.com/28956675/87110748-225df300-c2ab-11ea-9fe3-4e5decb75d62.png)


the formatting removes the !
![image](https://user-images.githubusercontent.com/28956675/87110784-3144a580-c2ab-11ea-836d-cfd0acc9fd51.png)

the file must have the right break lines. as below and it will format and work as expected
![image](https://user-images.githubusercontent.com/28956675/87110736-170ac780-c2ab-11ea-8b35-1bf8261717c0.png)


Thanks @chrisotto6  for taking the time to sort out this problem between keyboard and chair (and apologies, I should have also put in the code rather than the screenshot only in my previous post)

**Comment by chrisotto6** [comment]
@troyyer no problem at all thanks for taking the time to log an issue. Have a good week! 🥂
