### ISSUE TITLE
Add support for java environment properties

### ISSUE THREAD

**Issue by Nikscorp** [chrisotto6/VSCodeFitNesse#38]
**Proposal:**
Add ability to set java environment properties (1 or more) in user settings:

**Example:** (uesr settings)
```
"fitnesse.javaEnvironmentProperties": {
        "Key": "Value"
 }
```

**Launch:**
```shell
java -Xmx768m -DKey="Value" -jar C:\dev\fitnesse.jar -p 8080 -d c:\dev\fitnesse\ -c FrontPage.Test?test^&format=text
```

**Test:** (supported by FitNesse)
```
!|inspect query|select '${Key}'|
```

**Output:**
```
Value
```

Thank You!

**Comment by chrisotto6** [comment]
I don't think I'll ever get around to this, if you want to contribute it. By all means feel free.
