### ISSUE TITLE
Setting the location of my fitnesse standalone Jar file

### ISSUE THREAD

**Issue by mikeasage** [chrisotto6/VSCodeFitNesse#41]
When I run the test, the output java command looks like this:

java -Xmx768m -jar C:\someLocation\testing\fitnesse\fitnesse-standalone.jar -p 8080 -d c:\FitNesse\ -c ?test^&format=text

It seems the default expected location for the fitnesse-standalone.jar file is that someLocation path.  How do I update this to something else?  Or if there isn't some way to do this, it seems like this would be a great thing to add.

**Comment by mikeasage** [comment]
I found this in the settings.  For those having this trouble, got to Settings in VS Code.  Search for fitnesse, and you will find all the fitnesse settings.  Create an override in the user settings to update to where your jar file is located.

**Comment by chrisotto6** [comment]
@mikeasage that is called out in the ReadMe.md of the repository as well for required configuration. That as well as the java memory setting and port for FitNesse to use are required. Sorry for the delayed reply.
