### ISSUE TITLE
No formatter for "fitnesse"-files installed

### ISSUE THREAD

**Issue by chrosim** [chrisotto6/VSCodeFitNesse#71]
## 👣 Steps to reproduce
Open a fitnesse content.txt and execute cmd "format document" or save the changed file

## 🔬 Expected behavior
Fitnesse file should be formatted

## 🌳 Environment
- VS Code FitNesse Version [1.4.6]
- VS Code Info
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Datum: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Windows_NT x64 10.0.18362

**Comment by chrisotto6** [comment]
Upon looking more at the documentation vs code has default format functionality and currently this extension is not registered for it. I created #73 to follow up and resolve this issue further.
