### ISSUE TITLE
When to support .wiki format

### ISSUE THREAD

**Issue by zhongwei1981** [chrisotto6/VSCodeFitNesse#75]
When do you plan to format .wiki? I see it's a know issue for you.

**Comment by chrisotto6** [comment]
I no longer use FitNesse professionally which was my main motivation for creating this. So I'm not super motivated to add support for it but if you want to put down some requirements for what you expect I may get to it eventually. Sorry, this may not be answer you are looking for but I don't want to outright shoot it down.

**Comment by reators** [comment]
Hi @chrisotto6,
I'm also interested in the support of files with .wiki extension, especially for highlighting.
I'd like to use this extension, but in our project content.txt files are rather empty. All tests are located in .wiki files.
So I cannot use this extension without the support of .wiki files.
Maybe you can find some time to add this :)

**Comment by chrisotto6** [comment]
Resolved this ticket and published a version to the market place. @zhongwei1981 and @reators you'll need to update the extension in order to pick the up the changes.

**Comment by reators** [comment]
> Resolved this ticket and published a version to the market place. @zhongwei1981 and @reators you'll need to update the extension in order to pick the up the changes.

Thanks so much for this super-fast reaction. VSCode offered an update today and formatting works like a charm now!
